version: "1"
rules:
  - base: master
    upstream: jiayaoO3O:master
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: dev
    upstream: master
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1