name: py

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/py.yml' # 工作流定义
      - 'py/workflow_download.py' # 下载脚本
      - 'assets/config/option_workflow_download.yml' # 配置文件

jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      JM_USERNAME: ${{ secrets.JM_USERNAME }}
      JM_PASSWORD: ${{ secrets.JM_PASSWORD }}
      JM_DOWNLOAD_DIR: /home/runner/work/18-comic-finder/download/
      ZIP_NAME: '本子.tar.gz'
      UPLOAD_NAME: '下载完成的本子'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 安装依赖项（pip）
        run: |
          python -m pip install --upgrade pip
          pip install jmcomic -i https://pypi.org/project --upgrade

      # - name: 安装依赖项（local） 
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install commonX -i https://pypi.org/project --upgrade
      #     pip install -e ./

      - name: 运行下载脚本
        continue-on-error: true
        run: |
          cd ./py/
          python workflow_download.py

      - name: 压缩文件
        run: |
          cd $JM_DOWNLOAD_DIR
          tar -zcvf ../$ZIP_NAME ./
          mv ../$ZIP_NAME .

      - name: 上传结果
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.JM_DOWNLOAD_DIR }}/${{ env.ZIP_NAME }}
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          retention-days: 10